/**
 * Global site configuration.
 *
 * Put anything here that is NOT section copy: brand name, URLs, SEO defaults,
 * and feature flags that turn whole sections or claims on/off.
 */
export const siteConfig = {
  name: "Dagsis",
  tagline: "AI Agents That Know Your Business",
  description:
    "Dagsis turns your documents, website and FAQs into AI agents that answer customers on your website, WhatsApp, Instagram, Facebook, Telegram and Discord.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://dagsis.com",

  links: {
    // TODO: point these at the real app / booking URLs.
    signUp: "https://app.dagsis.com/signup",
    signIn: "https://app.dagsis.com/login",
    bookDemo: "#book-demo",
    contactSales: "mailto:sales@dagsis.com",
    // PLACEHOLDER walkthrough generated by `npm run media:placeholders`.
    // Replace the file, or set a YouTube/Vimeo embed URL instead.
    productVideo: "/videos/product-walkthrough.mp4",
    productVideoPoster: "/images/video-poster.webp",
  },

  social: {
    twitter: "https://x.com/dagsis",
    linkedin: "https://www.linkedin.com/company/dagsis",
  },
} as const;

/**
 * Feature flags. Flip these when the business is ready — no code changes
 * needed in the sections themselves.
 */
export const featureFlags = {
  /** Brief: "Trusted By / Social Proof (not needed right now)". */
  showTrustedBy: false,
  /** Only enable once testimonial copy is real and approved. */
  showTestimonial: true,
  /** Brief: show "No credit card required" ONLY if accurate. */
  noCreditCardRequired: false,
  /** Show yearly/monthly toggle on the pricing preview. */
  showBillingToggle: true,
} as const;

export type SiteConfig = typeof siteConfig;
