import {
  BarChart3,
  Bot,
  Database,
  MessageSquareText,
  PanelBottom,
  Share2,
} from "lucide-react";
import type { Feature, SectionIntro } from "@/types/content";

export const featuresIntro: SectionIntro = {
  eyebrow: "Platform",
  title: "Everything your AI agent needs",
  description:
    "Build the agent, put it where your customers are, and see what they ask. That's the whole product.",
};

/**
 * Backgrounds behind the frosted feature cards: mesh gradients in the logo
 * colours. Cycled in order. Generated by `npm run media:placeholders`
 * (src/components/dev/FeatureScenes.tsx).
 */
export const featureBackgrounds = [0, 1, 2, 3].map((i) => `/images/features/bg-${i}.webp`);

export const features: Feature[] = [
  {
    icon: Database,
    title: "Knowledge Base",
    description:
      "Import PDFs, docs, web pages and FAQs. Keep answers accurate with automatic re-syncing.",
    stat: { value: "PDF · DOCX · URLs", label: "Sources your agent learns from" },
    image: { src: "/images/features/scene-knowledge.webp", alt: "Knowledge base with product catalog, website and returns policy synced" },
  },
  {
    icon: Bot,
    title: "AI Agent Builder",
    description:
      "Set the name, tone, goals and limits in a form, then try it out before anyone else sees it.",
    stat: { value: "No code", label: "Tone, goals and guardrails in one form" },
    image: { src: "/images/features/scene-builder.webp", alt: "Agent settings for Ava: tone, answer only from docs, hand off refunds" },
  },
  {
    icon: PanelBottom,
    title: "Web Widget",
    description:
      "A fully brandable chat widget you can drop on any site with a single line of code.",
    stat: { value: "1 line", label: "Of code to go live on your website" },
    image: { src: "/images/features/scene-widget.webp", alt: "A store website with the Dagsis chat widget answering a sizing question" },
  },
  {
    icon: Share2,
    title: "Multi-channel",
    description:
      "One agent, every channel: website, WhatsApp, Instagram, Facebook, Telegram and Discord, all in sync.",
    stat: { value: "6 channels", label: "Web, WhatsApp, Instagram, Facebook & more" },
    image: { src: "/images/features/scene-channels.webp", alt: "A WhatsApp chat with the Dagsis assistant, plus website, Telegram and Discord" },
  },
  {
    icon: MessageSquareText,
    title: "Conversations",
    description:
      "See every conversation in one inbox. Jump in, take over, or hand back to the agent anytime.",
    stat: { value: "1 inbox", label: "Every channel, one-click takeover" },
    image: { src: "/images/features/scene-conversations.webp", alt: "The shared inbox with chats from WhatsApp, website, Telegram and Discord" },
  },
  {
    icon: BarChart3,
    title: "Analytics",
    description:
      "Track volume, resolution rate and top questions to find gaps in your knowledge.",
    stat: { value: "Top questions", label: "See what customers ask most" },
    image: { src: "/images/features/scene-analytics.webp", alt: "Analytics showing 86% resolved by AI and the top customer questions" },
  },
];

/** Pills under the ticker (reference: "10,000+ Users · 4.9 Rating · …"). Keep factual. */
export const featureChips = ["No-code setup", "6 channels", "Human handoff", "Analytics built in"];
