import { BarChart3, Bot, Database, MessageSquareText, PanelBottom } from "lucide-react";
import { siteConfig } from "@/config/site";
import type { SectionIntro, ShowcaseTab } from "@/types/content";

export const showcaseIntro: SectionIntro = {
  eyebrow: "Product tour",
  title: "See Dagsis",
  titleAccent: "at work",
  description: "Five stops, from uploading your docs to seeing what customers ask. Keep scrolling to move through the tour.",
};

export const showcaseTour = {
  /** Hint in the footer while the tour is pinned. */
  scrollHint: "Scroll to explore the product",
  /** Buttons after the tour, same style as the rest of the site. */
  primaryCta: { label: "Book a Demo", href: siteConfig.links.bookDemo },
  secondaryCta: { label: "Start for Free", href: siteConfig.links.signUp },
};

/**
 * PLACEHOLDER 16:9 product scenes (src/components/dev/TourShot.tsx), generated by
 * `npm run media:placeholders` (see scripts/). Replace the files in
 * public/images/showcase/ with real Dagsis screenshots (same names, 16:9),
 * or point `src` at new files. Size is the file's pixel size.
 */
const shot = (id: string, alt: string) => ({
  type: "image" as const,
  src: `/images/showcase/tour-${id}.webp`,
  alt,
  width: 1600,
  height: 900,
});

/**
 * Each tab is one stop on the tour: `title` is the card title, and
 * `label` + the first two `bullets` form the small grey meta line.
 *
 * Other options per tab: `{ type: "video", src: "/videos/x.mp4", poster }`
 * or `{ type: "mock", variant: "knowledge" }` for the live coded UI.
 */
export const showcaseTabs: ShowcaseTab[] = [
  {
    id: "knowledge",
    note: "Sources synced",
    label: "Knowledge",
    icon: Database,
    title: "All your answers, in one place",
    description: "Drop in files and links. Dagsis indexes them so your agent answers from facts, not guesses.",
    bullets: ["PDF, DOCX, TXT & URLs", "Automatic website crawl", "Scheduled re-sync"],
    media: shot("knowledge", "Dagsis knowledge base with synced PDFs and web pages"),
  },
  {
    id: "builder",
    note: "Agent Ava is ready",
    label: "Agents",
    icon: Bot,
    title: "Design an agent in minutes",
    description: "Set persona, tone and goals, then preview replies side by side before going live.",
    bullets: ["Tone & persona presets", "Guardrails & handoff rules", "Live test playground"],
    media: shot("builder", "Dagsis agent builder with a live test chat"),
  },
  {
    id: "widget",
    note: "Widget live on yourstore.com",
    label: "Widget",
    icon: PanelBottom,
    title: "A widget that matches your brand",
    description: "Customize colors, avatar and greeting. Paste one snippet and you're live.",
    bullets: ["Brand colors & avatar", "Welcome messages", "One-line install"],
    media: shot("widget", "Dagsis chat widget on a store website"),
  },
  {
    id: "conversations",
    note: "You took over the chat",
    label: "Inbox",
    icon: MessageSquareText,
    title: "Every chat, one inbox",
    description: "Follow conversations across channels and take over whenever a human touch is needed.",
    bullets: ["Unified multi-channel inbox", "One-click takeover", "Conversation tags"],
    media: shot("conversations", "Dagsis inbox showing a WhatsApp conversation"),
  },
  {
    id: "analytics",
    note: "Weekly report ready",
    label: "Analytics",
    icon: BarChart3,
    title: "Know what customers ask",
    description: "Spot trends, measure resolution and find the questions your knowledge base is missing.",
    bullets: ["Resolution rate", "Top questions", "Channel breakdown"],
    media: shot("analytics", "Dagsis analytics with resolution rate and top questions"),
  },
];
